### ISSUE TITLE
How to open menu like in screenshot

### ISSUE THREAD

**Issue by zetrixweb** [SSA111/SSASideMenu#52]
![687474703a2f2f6469676974616c6c65617665732e636f6d2f626c6f672f77702d636f6e74656e742f75706c6f6164732f323031352f30332f68616d627572677565724d656e752e676966](https://cloud.githubusercontent.com/assets/15913477/14934821/df6ecff2-0eda-11e6-8d62-85983b6c8cc3.gif)

**Comment by zetrixweb** [comment]
i mean flat menu

**Comment by ZetrixWeb-iOS** [comment]
+1

**Comment by iamasimkhan** [comment]
I'm using this library 
https://github.com/SSA111/SSASideMenu
When it is used as it is, it works.
However, I'm implementing this for my overall app, I mean in every ViewController, I want to use the same side bar menu, that must appear on the click of Menu bar button item. Due to spare navigation problems I guess, is not working on navigation from one control to other.

On the front view controller it is working, but if I move to some other new controller that is having his own navigation controller, on I move by clicking sidebar menu items and segue to a controller embedded in navigation controller, it does not show sidebar menu.

**Comment by SSA111** [comment]
This feature is currently not supported. A PR implementing this feature is appreciated. Closing...
