### ISSUE TITLE
How to set statusBar is white?

### ISSUE THREAD

**Issue by nobeeJonh** [SSA111/SSASideMenu#55]

**Comment by pamik** [comment]
MenuViewController.swift:

`override func viewDidLoad() {`
`    super.viewDidLoad()`
`    self.sideMenuViewController?.statusBarStyle = .Light`
`}`

**Comment by iamasimkhan** [comment]
I'm using this library 
https://github.com/SSA111/SSASideMenu
When it is used as it is, it works.
However, I'm implementing this for my overall app, I mean in every ViewController, I want to use the same side bar menu, that must appear on the click of Menu bar button item. Due to spare navigation problems I guess, is not working on navigation from one control to other.

On the front view controller it is working, but if I move to some other new controller that is having his own navigation controller, on I move by clicking sidebar menu items and segue to a controller embedded in navigation controller, it does not show sidebar menu.

**Comment by SSA111** [comment]
I assume this is fixed by @pamik comment? .. Closing.
